# Generated by Django 4.1.9 on 2023-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='graduated',
            field=models.BooleanField(default=False, help_text='Is student already graduated?', verbose_name='Graduated'),
        ),
    ]
