# Generated by Django 4.1.7 on 2023-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_studentdetail_graduated"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdetail",
            name="year_joined",
            field=models.PositiveIntegerField(default=2023, verbose_name="Year Joined"),
        ),
    ]
