# Generated by Django 4.1.10 on 2023-07-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_studentdetail_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetail',
            name='permissions',
            field=models.JSONField(default=dict, help_text='Permissions of the staff member', verbose_name='Permissions'),
        ),
    ]
