# Generated by Django 4.1.10 on 2023-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_staffdetail_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permissions of the staff member', null=True, verbose_name='Permissions'),
        ),
    ]
