# Generated by Django 4.1.10 on 2023-07-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_staffdetail_permissions'),
        ('data', '0003_studentdetail_year_joined'),
    ]

    operations = [
    ]
