# Generated by Django 4.1.10 on 2023-07-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_studentdetail_year_joined'),
        ('data', '0004_alter_staffdetail_permissions'),
    ]

    operations = [
    ]
