# Generated by Django 4.1.10 on 2023-08-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_rename_study_resources_department_study_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='locked',
            field=models.BooleanField(default=False, help_text='Is the department locked?', verbose_name='Locked'),
        ),
    ]
