# Generated by Django 4.1.10 on 2023-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_merge_20230714_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Weightage',
            new_name='weightage',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='T1',
            new_name='t1',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='T1_file',
            new_name='t1_file',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='T2',
            new_name='t2',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='T2_file',
            new_name='t2_file',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='T3',
            new_name='t3',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='T3_file',
            new_name='t3_file',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='T4',
            new_name='t4',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='T4_file',
            new_name='t4_file',
        ),
        migrations.RemoveField(
            model_name='studentsemesterrecord',
            name='MOOC_courses',
        ),
        migrations.AlterField(
            model_name='department',
            name='study_resources',
            field=models.ManyToManyField(blank=True, to='data.studyresource', verbose_name='Study Resources'),
        ),
        migrations.AlterField(
            model_name='staffdetail',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permissions of the staff member', null=True, verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='group_project',
            field=models.ManyToManyField(blank=True, to='data.groupproject', verbose_name='Group Project'),
        ),
        migrations.AlterField(
            model_name='studentsemesterrecord',
            name='individual_project',
            field=models.ManyToManyField(blank=True, to='data.individualproject', verbose_name='Individual Project'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='remedial_result',
            field=models.ManyToManyField(blank=True, to='data.remedialtestresult', verbose_name='Remedial Result'),
        ),
        migrations.AddField(
            model_name='studentsemesterrecord',
            name='mooc_courses',
            field=models.ManyToManyField(blank=True, to='data.moocresult', verbose_name='MOOC Courses'),
        ),
    ]
