# Generated by Django 4.1.10 on 2023-07-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_rename_weightage_subject_weightage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsemesterrecord',
            old_name='mooc_courses',
            new_name='mooc_course',
        ),
    ]
