# Generated by Django 4.1.10 on 2023-07-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_merge_20230714_1448'),
        ('data', '0006_alter_department_batch_alter_department_semester_and_more'),
    ]

    operations = [
    ]
