# Generated by Django 4.1.10 on 2023-07-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_mooc_courses_studentsemesterrecord_mooc_course'),
        ('data', '0007_merge_20230719_1206'),
    ]

    operations = [
    ]
