# Generated by Django 4.1.10 on 2023-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_merge_20230721_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='weightage',
            field=models.ManyToManyField(blank=True, help_text='Weightage distribution of the subject', to='data.weightage', verbose_name='Weightage'),
        ),
    ]
