# Generated by Django 4.1.10 on 2023-07-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_subject_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='faculty',
            field=models.ManyToManyField(blank=True, help_text='Faculty allocated to batch', to='data.facultyallocation', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='student',
            field=models.ManyToManyField(blank=True, help_text='Student allocated to batch', to='data.studentdetail', verbose_name='Student'),
        ),
    ]
