# Generated by Django 4.1.10 on 2023-07-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_batch_faculty_alter_batch_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecture_no',
            field=models.CharField(default=0, max_length=1, verbose_name='Lecture No.'),
        ),
    ]
