# Generated by Django 4.1.10 on 2023-08-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_studentsemesterrecord_attendance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='study_resources',
            new_name='study_resource',
        ),
    ]
